---
apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-service-config
data:
  PORT: '4000'
  RESPONSE_TIME: '100'
  CPU_RATIO: '20'
  FAILURE_RATE: '1'
  FAILURE_OVERHEAD: '10'

---
apiVersion: v1
kind: Service
metadata:
  name: greeting-service
  labels:
    app: greeting-service
  annotations:
    metrics.dynatrace.com/scrape: 'true'
    metrics.dynatrace.com/path: 'metrics'
    metrics.dynatrace.com/port: '4000'
    metrics.dynatrace.com/secure: 'false'
    metrics.dynatrace.com/filter: |
      {
        "mode": "include",
        "names": [ "app_request_count_total" ]
      }
spec:
  selector:
    app: greeting-service
  ports:
    - name: http
      port: 4000
      targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeting-service
    app.kubernetes.io/name: greeting-service
    app.kubernetes.io/version: 0.4.10
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: greeting-service
    app.kubernetes.io/managed-by: manifests
    app.kubernetes.io/created-by: admin
  name: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
        - name: greeting-service
          image: martinnirtl/demos.general.greeting-service:0.4.10
          # resources: {}
          resources:
            requests:
              memory: "180M"
              cpu: "700m"
            limits:
              memory: "300M"
              cpu: "700m"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: greeting-service-config
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
