---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-tests
data:
  simple.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export default function () {
      http.get(__ENV.GREETING_SERVICE_BASEURL + '/hello/martin');
      sleep(1);
    }
  load.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export const options = {
      stages: [
        { duration: '20m', target: 10 },
        { duration: '20m', target: 10 },
        { duration: '10m', target: 20 },
        { duration: '10m', target: 20 },
        { duration: '10m', target: 0 },
      ],
    };

    export default function () {
      http.get(__ENV.GREETING_SERVICE_BASEURL + '/hello/martin');
      sleep(1);
    };

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-static
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: loadimpact/k6
            imagePullPolicy: IfNotPresent
            args:
            - run
            - "--vus=20"
            - "--duration=1m"
            - simple.js
            env:
            - name: GREETING_SERVICE_BASEURL
              value: http://greeting-service:4000
            volumeMounts:
              - mountPath: /home/k6
                name: config
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: k6-tests

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-daily
spec:
  schedule: "* 6 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: loadimpact/k6
            imagePullPolicy: IfNotPresent
            args:
            - run
            - load.js
            env:
            - name: GREETING_SERVICE_BASEURL
              value: http://greeting-service:4000
            volumeMounts:
              - mountPath: /home/k6
                name: config
          restartPolicy: OnFailure
          volumes:
            - name: config
              configMap:
                name: k6-tests