receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["greeting-service:4000"]

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:

exporters:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/examples/demo/otel-collector-config.yaml
  prometheus:
    endpoint: "0.0.0.0:8889"
    # const_labels:
    #   label1: value1

  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

  otlp:
    endpoint: tempo:4317
    insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, otlp]
